sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: mc1Q9yWgSfm4yrFNLmj/AAmVKS+5No4auWsft9jQnF9cDhZ9lcf9MOJfkn17ufpcEdeKWtcSe8fHXKyQkzjR4TQoVEhi7acvE6gvww8DDRd6XtY3+8BV05fZuivCKdrGZpp+4fC/rLUjBv0kdpiAZfMDd03BzjolNCEGl/yzOs6b3Q9m/YDaW6cpA5Ewnr3d+R6VEemhotQt7BBOkprhF7gSniVlYrdbxrdmd36M+oIaGAtf0nFgH6XhWQlf58wXh5A/XPvlioP8yu9KBS1OuAlGhVH/xauC2gIAj+GuER7YowVDu4APZIVmO5sAJO6GghaklrIIUC1nYWqESz9bx2dH7/1wxw95kz5/VCl8ej+01x+5TYL5BWQX0oBMKNwRt6XaHEarFCN4ECPKmZptdflFycE4Ii7ZC+gcK//1q006dhR3J3ngzz+Tkp7+PePy/aEw4ksic0fN01zDLFSOW3ynyo9/6/c6AG5sxYGwMszqQ2LHV8YOeI8vbL36NnVb2iC9+8dHPusrnb1ykgkU5Hj15FSZdq7pD32+5bBytHlSvkXWmzXIlyDaANbCoramySWeaH9pOpsR64wm3ZvwhrgeMTCzvAJeGlEXmJaKi3+DFg1PKKtREAc3k8MCAJU5aB6mByJP+yd1IKukrHkRu1r0nKQUIlK6WzeUGl95Jb4=}, {secure: pqU59JQNnlCEmbT8yawcTJR9QIGo6rf4qGm5AcMx334vPoiF4y6dofdr+1NhCQPQI4zkqiD0mbqdVIrda7pb5fdJqFCdcHnZ9BOZqLb0FrBLbFT2Hif6RH/eOz30uWBOu67fdv+JcpS2ohiVcQreOSMes1Ddn5an6BW4bP/sqopWwWmf1yQ6aZdnXkS0xWB0yGaCvowxXofrlajxstOZxEUkRDyc06nNsbrS92KjPhoV6QWw0snj7dtgkJwDxcQDirL8ar46APdwy/Kt9c4mRgDOexsQmr/Qg/+G7RdHdxaS/UwEdQGXcCt06VwLwOU1mQ5rVOjzrQfXxMBKrFcgQPOqQ3CHazTaTUW2peEhZJZbeeZNVo7EU6Xja1E9j7jYs2EmCPqybjikEUEMOeEd1Sks1JTD6yqJTtgcLorEXAUg56t4I8uIXsyVvMsU6Z717bbuwNQLJIO9+6ltNbLJETuPvAzB3tbZPE2o8JEQzkCMAhJC6qWUbr46s75YOLU63J/AWVTJOKG8ay88PojOADqbfveZ9fUBnRljzMkud+rsbnCUu9ICciR+LGDcVrkD77ROTQqFAhgnNi+FdXyaCG1BMKbudxtT8OdJuxw3MEvvMvioHoOV7yX6U+7ntcfmWIHR0VWynjtfn0luAOurjntfl9yihbfefbmSfspEV4g=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
